### ISSUE TITLE
Command failed: node_modules/serverless/bin/serverless deploy

### ISSUE THREAD

**Issue by mjcguada** [pharindoko/json-serverless#361]
Hi! I've been trying to deploy a server with a basic json and I get the following error everytime:
![image](https://user-images.githubusercontent.com/22896054/81477032-8dd90500-9215-11ea-8dca-8aa1a62f64d7.png)

I used this api in march 2020 and it worked perfectly. This time I've set the credentials, config, etc. exactly the same but I can't make it work

Thanks for your help

**Comment by pharindoko** [comment]
Hey, in the background the serverless framework will be used.
Please do following:

Go into the stackfolder where the serverless.yml file exists and execute the command:
sls deploy

Hope this helps - let me know what‘s the issue ...

br, 

Flo

**Comment by mjcguada** [comment]
It worked perfectly, thank you so much for your help and your software :)

**Comment by hjiedueh** [comment]
Hi I'm having the same issue, and when I try to run sls deploy the command prompt says that sls isn't a recognized command. I'm sure there's something I'm missing; andy help would be really appreciated.

**Comment by pharindoko** [comment]
> Hi I'm having the same issue, and when I try to run sls deploy the command prompt says that sls isn't a recognized command. I'm sure there's something I'm missing; andy help would be really appreciated.

Hmm thanks for letting me know about this.
Will test it asap.

**Comment by pharindoko** [comment]
Ok I just verified that this is no general issues:
Your issue happens when the solution get`s deployed.

Please go into the stackfolder and execute following statement:
```
SLS_DEBUG=* npx serverless deploy
```

This should show you all actions that happen on deployment and give you a clear hint what might be the issue.
