### ISSUE TITLE
How do I customize the interface method?

### ISSUE THREAD

**Issue by huangfushan** [pharindoko/json-serverless#803]
Hi,I think this plug-in is great, but I have a small question.

1、create db.json
```
{
    "posts": [
      { "id": 1, "title": "json-server", "author": "typicode" },
      { "id": 2, "title": "test", "author": "yourAuthor" }
    ],
    "comments": [
      { "id": 1, "body": "some comment", "postId": 1 }
    ],
    "profile": { "name": "typicode" }
}
```
2、`jsonsls run db.json`
 
After operating according to the prompts, it is found that all methods will be generated as much as possible

I noticed that the'profile' interface generates four different methods: get, post, delete, and patch. Suppose I only want to generate get and post among them. Do not want to generate delete, patch. How should it be configured?

Thanks !

**Comment by pharindoko** [comment]
Hi @huangfushan,
currently there's only the option to switch between readonly/all http verbs but I like your request.
Will try to implement a feature to set the verbs separately 'til mid of July. (Currently I'm on vacation)

 
Shortterm: (if you need a solution now...)
- create the serverless solution via template directly (see readme)
- create a middleware to restrict access to specific http verbs ...
